### ISSUE TITLE
Request to enhance Bond CNI to use resources discovered via the sriov device plugin

### ISSUE THREAD

**Issue by svallala** [intel/bond-cni#3]
Bond CNI, currently is expecting that the VF names be manually provided. This won't be scalable and does not fit well with the Intel SRIOV device plugin flow, where the VFs are allocated based on the k8s resource names.

1. Requesting Bond CNI to be enhanced to use resource names.
2. Control the name of the interface inside the container

The network attachment definition could be something as shown below. In this case, VFs are from the same PFs, but could also be from different PFs.

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bond-net
  namespace: kube-system
spec:
  config: '{
  "cniVersion": "0.3.1",
  "name": "bond-network",
  "plugins": [
    {
        "type": "bond",
        "ifname": "bond0",
        "mode": "active-backup",
        "miimon": "100",
        "links": [
                {
                  "k8s.v1.cni.cncf.io/resourceName: "intel.com/sriov0",
                  "name": "net0"
                },
                { 
                  "k8s.v1.cni.cncf.io/resourceName": "intel.com/sriov0",
                  "name": "net1"
                }
        ],

        "ipam": {
             "type": "host-local",
             "subnet": "192.168.1.0/24",
             "rangeStart": "192.168.1.21",
             "rangeEnd": "192.168.1.30",
             "routes": [
                  { "dst": "0.0.0.0/0" }
             ],
             "gateway": "192.168.1.1"
        }
    }
  ]
}'

Then the pod can be deployed using following spec:

apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/bond-net
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/sriov0: '2'
      limits:
        intel.com/sriov0: '2'

**Comment by killianmuldoon** [comment]
@svallala  I think the process describe in PR#4 should meet this use case. I'll merge it once it's reviewed.

**Comment by killianmuldoon** [comment]
@svallala - can you see if the new process in the readme works for you?

**Comment by svallala** [comment]
@killianmuldoon specified steps in the README works fine. You should remove the IP addresses assigned to the slave interfaces

**Comment by killianmuldoon** [comment]
@svallala  good catch! I'll do that in the next update. Thanks
